name: portifolio_web
description: "Portifolio Daniel Pacheco Ferreira."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.0-127.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  gap: ^3.0.1
  url_launcher: ^6.3.2
  web: ^1.1.1
  provider: ^6.1.5+1
  web_smooth_scroll: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/pdf/
    - assets/sobre/
    - assets/projetos/blitz/
    - assets/projetos/sea_adventure/
    - assets/projetos/bluecat_compras/
    - assets/projetos/chat_online/
    - assets/projetos/datarey_mobile/
    - assets/projetos/bluecat_dashboard/
    - assets/projetos/datafarma_venda/
    - assets/projetos/portifolio/
